jobs:
  actionlint:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6
      with:
        allowed-endpoints: 'api.github.com:443 github.com:443

          '
        disable-sudo: true
        egress-policy: block
    - continue-on-error: true
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      env:
        SHELLCHECK_OPTS: -e SC2001 -e SC2035 -e SC2046 -e SC2061 -e SC2086 -e SC2156
      name: actionlint
      uses: reviewdog/action-actionlint@fd627997c9688c2f39e13917aed23873c031b834
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-check
name: actionlint
on:
  repository_dispatch:
    types: trigger-ga___actionlint.yml
permissions: read-all
