env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
  PUBLISH_JDK: 21
jobs:
  benchmarks:
    env:
      JAVA_VERSION: ${{ matrix.java }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6
      with:
        allowed-endpoints: 'api.adoptium.net:443 api.github.com:443 caffeine.gradle-enterprise.cloud:443
          download.java.net:443 download.oracle.com:443 downloads.gradle.org:443 downloads.gradle-dn.com:443
          gds.oracle.com:443 github.com:443 jcenter.bintray.com:443 objects.githubusercontent.com:443
          plugins.gradle.org:443 plugins-artifacts.gradle.org:443 repo.maven.apache.org:443
          repo1.maven.org:443 raw.githubusercontent.com:443 services.gradle.org:443
          www.graalvm.org:443

          '
        disable-sudo: true
        egress-policy: block
    - continue-on-error: true
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      name: Compute JMH Benchmark
      uses: ./.github/actions/run-gradle
      with:
        arguments: 'caffeine:jmh --no-daemon -q -PincludePattern=ComputeBenchmark
          -PbenchmarkParameters=computeType=Caffeine,Guava,ConcurrentHashMap

          '
        java: ${{ matrix.java }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      if: 'github.event_name == ''push'' && github.event.repository.fork == false
        && endsWith(github.ref, github.event.repository.default_branch)

        '
      name: Upload Compute JMH Results to Gist
      uses: popsiclestick/gist-sync-action@88f8633178625914f2a01abf1a765f7272a580fa
      with:
        auth: ${{ secrets.GIST_TOKEN }}
        gist_description: Compute JMH Results
        gist_title: compute_results_${{ matrix.java }}.json
        gist_url: https://gist.githubusercontent.com/ben-manes/511298014cc5629cbc5e57f09fd4c430
        github_file: ./caffeine/build/reports/jmh/results.json
    - continue-on-error: true
      name: Get/Put JMH Benchmark
      uses: ./.github/actions/run-gradle
      with:
        arguments: 'caffeine:jmh --no-daemon -q -PincludePattern=GetPutBenchmark -PbenchmarkParameters=cacheType=Caffeine,Guava,ConcurrentHashMap

          '
        java: ${{ matrix.java }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      if: 'github.event_name == ''push'' && github.event.repository.fork == false
        && endsWith(github.ref, github.event.repository.default_branch)

        '
      name: Upload Get/Put JMH Results to Gist
      uses: popsiclestick/gist-sync-action@88f8633178625914f2a01abf1a765f7272a580fa
      with:
        auth: ${{ secrets.GIST_TOKEN }}
        gist_description: Get/Put JMH Results
        gist_title: getput_results_${{ matrix.java }}.json
        gist_url: https://gist.githubusercontent.com/ben-manes/b231cf57cf8e144e2247716e777edcf3
        github_file: ./caffeine/build/reports/jmh/results.json
    - continue-on-error: true
      name: Put/Remove JMH Benchmark
      uses: ./.github/actions/run-gradle
      with:
        arguments: 'caffeine:jmh --no-daemon -q -PincludePattern=PutRemoveBenchmark
          -PbenchmarkParameters=cacheType=Caffeine,Guava,ConcurrentHashMap

          '
        java: ${{ matrix.java }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: FrequencySketch JMH Benchmark
      uses: ./.github/actions/run-gradle
      with:
        arguments: 'caffeine:jmh --no-daemon -q -PincludePattern=FrequencySketchBenchmark
          -PbenchmarkParameters=tableSize=134217728

          '
        java: ${{ matrix.java }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: TimerWheelBenchmark JMH Benchmark
      uses: ./.github/actions/run-gradle
      with:
        arguments: caffeine:jmh --no-daemon -q -PincludePattern=TimerWheelBenchmark
        java: ${{ matrix.java }}
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      if: 'matrix.java == env.PUBLISH_JDK && github.event_name == ''push'' && endsWith(github.ref,
        github.event.repository.default_branch)

        '
      name: Publish JMH benchmarks
      run: "{\n  echo '#### [Compute](https://jmh.morethan.io/?gists=511298014cc5629cbc5e57f09fd4c430)'\n\
        \  echo -n 'This benchmark that evaluates the overhead due to locking when\
        \ the entry is'\n  echo -n 'present. The scenarios graphed are all threads\
        \ retrieving a single entry'\n  echo -n '(\"sameKey\") and threads retrieving\
        \ different keys based on a Zipf distribution'\n  echo -n '(\"spread\").'\n\
        \  echo -e '\\n'\n  echo '#### [Get/Put](https://jmh.morethan.io/?gists=b231cf57cf8e144e2247716e777edcf3)'\n\
        \  echo -n 'A benchmark that evaluates the read/write performance of a cache.\
        \ The cache is'\n  echo -n 'pre-populated for a 100% hit rate and a Zipf distribution\
        \ of keys is used to'\n  echo -n 'mimic application usage patterns.'\n} >>\
        \ $GITHUB_STEP_SUMMARY\n"
    strategy:
      matrix:
        java:
        - 11
        - 21
        - 23
        - GraalVM
name: benchmarks
on:
  repository_dispatch:
    types: trigger-ga___benchmarks.yml
permissions: read-all
