jobs:
  security-scan:
    if: github.event.repository.fork == false
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6
      with:
        allowed-endpoints: 'api.codacy.com:443 api.github.com:443 auth.docker.io:443
          github.com:443 golang.org:443 objects.githubusercontent.com:443 production.cloudflare.docker.com:443
          raw.githubusercontent.com:443 registry-1.docker.io:443 *.blob.core.windows.net:443

          '
        disable-sudo: true
        egress-policy: block
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      name: Run Codacy Analysis
      uses: codacy/codacy-analysis-cli-action@master
      with:
        format: sarif
        gh-code-scanning-compat: true
        max-allowed-issues: 2147483647
        output: results.sarif
    - continue-on-error: true
      id: check_files
      name: Check file existence
      uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6
      with:
        files: results.sarif
    - continue-on-error: true
      if: steps.check_files.outputs.files_exists == 'true'
      name: Remove duplicate runs
      run: jq -c '.runs |= unique_by({tool, invocations, results})' < results.sarif
        > codacy.sarif
    - continue-on-error: true
      if: steps.check_files.outputs.files_exists == 'true'
      name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@2e230e8fe0ad3a14a340ad0815ddb96d599d2aff
      with:
        sarif_file: codacy.sarif
    timeout-minutes: 15
name: Codacy
on:
  repository_dispatch:
    types: trigger-ga___codacy.yml
permissions: read-all
