env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
  JAVA_VERSION: 21
jobs:
  dependency-submission:
    permissions:
      contents: read
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6
      with:
        allowed-endpoints: 'api.adoptium.net:443 api.github.com:443 caffeine.gradle-enterprise.cloud:443
          downloads.gradle.org:443 downloads.gradle-dn.com:443 github.com:443 jcenter.bintray.com:443
          objects.githubusercontent.com:443 plugins.gradle.org:443 plugins-artifacts.gradle.org:443
          repo.maven.apache.org:443 repo1.maven.org:443 services.gradle.org:443

          '
        disable-sudo: true
        egress-policy: block
    - continue-on-error: true
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}
    - continue-on-error: true
      name: Submit Dependency Graph
      uses: gradle/actions/dependency-submission@db19848a5fa7950289d3668fb053140cf3028d43
      with:
        cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
        dependency-graph: generate-and-upload
name: Generate and save dependency graph
on:
  repository_dispatch:
    types: trigger-ga___dependency-submission-pr-submit.yml
permissions: read-all
