env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
  JAVA_VERSION: 22
jobs:
  submit-dependency-graph:
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6
      with:
        allowed-endpoints: 'api.adoptium.net:443 api.github.com:443 caffeine.gradle-enterprise.cloud:443
          downloads.gradle.org:443 downloads.gradle-dn.com:443 github.com:443 jcenter.bintray.com:443
          objects.githubusercontent.com:443 plugins.gradle.org:443 plugins-artifacts.gradle.org:443
          repo.maven.apache.org:443 repo1.maven.org:443 services.gradle.org:443

          '
        disable-sudo: true
        egress-policy: block
    - continue-on-error: true
      name: Retrieve and submit dependency graph
      uses: gradle/actions/dependency-submission@db19848a5fa7950289d3668fb053140cf3028d43
      with:
        dependency-graph: download-and-submit
name: Retrieve and submit dependency graph
on:
  repository_dispatch:
    types: trigger-ga___dependency-submission-pr-retreive.yml
permissions: read-all
