env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
  JAVA_VERSION: 22
jobs:
  dependency-check:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6
      with:
        allowed-endpoints: 'api.adoptium.net:443 api.github.com:443 caffeine.gradle-enterprise.cloud:443
          downloads.gradle.org:443 downloads.gradle-dn.com:443 github.com:443 jcenter.bintray.com:443
          jeremylong.github.io:443 nvd.nist.gov:443 objects.githubusercontent.com:443
          ossindex.sonatype.org:443 plugins.gradle.org:443 plugins-artifacts.gradle.org:443
          repo.maven.apache.org:443 repo1.maven.org:443 raw.githubusercontent.com:443
          services.gradle.org:443 www.cisa.gov:443

          '
        disable-sudo: true
        egress-policy: block
    - continue-on-error: true
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      name: Run dependency-check
      uses: ./.github/actions/run-gradle
      with:
        arguments: dependencyCheckAggregate --no-configuration-cache
        java: ${{ env.JAVA_VERSION }}
    - continue-on-error: true
      id: check_files
      name: Check file existence
      uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6
      with:
        files: build/reports/dependency-check-report.sarif
    - continue-on-error: true
      if: steps.check_files.outputs.files_exists == 'true'
      name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@2e230e8fe0ad3a14a340ad0815ddb96d599d2aff
      with:
        sarif_file: build/reports/dependency-check-report.sarif
name: Dependency Check
on:
  repository_dispatch:
    types: trigger-ga___dependency-check.yml
permissions: read-all
