jobs:
  dependency-review:
    permissions:
      contents: read
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6
      with:
        allowed-endpoints: 'api.deps.dev:443 api.github.com:443 github.com:443

          '
        disable-sudo: true
        egress-policy: block
    - continue-on-error: true
      name: Checkout Repository
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      name: Dependency Review
      uses: actions/dependency-review-action@72eb03d02c7872a771aacd928f3123ac62ad6d3a
      with:
        comment-summary-in-pr: on-failure
        license-check: false
        retry-on-snapshot-warnings: true
        retry-on-snapshot-warnings-timeout: 600
name: Dependency Review
on:
  repository_dispatch:
    types: trigger-ga___dependency-review.yml
permissions: read-all
