env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
  JAVA_VERSION: 21
jobs:
  examples:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6
      with:
        allowed-endpoints: 'api.github.com:443 api.adoptium.net:443 caffeine.gradle-enterprise.cloud:443
          download.oracle.com:443 downloads.gradle.org:443 downloads.gradle-dn.com:443
          gds.oracle.com:443 github.com:443 jcenter.bintray.com:443 objects.githubusercontent.com:443
          plugins.gradle.org:443 plugins-artifacts.gradle.org:443 repo.maven.apache.org:443
          repo1.maven.org:443 services.gradle.org:443 www.graalvm.org:443

          '
        disable-sudo: true
        egress-policy: block
    - continue-on-error: true
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        distribution: temurin
        java-version: ${{ env.JAVA_VERSION }}
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@db19848a5fa7950289d3668fb053140cf3028d43
      with:
        add-job-summary: never
        cache-read-only: false
        gradle-home-cache-cleanup: true
    - continue-on-error: true
      name: Simulator
      run: './gradlew simulator:run -Dcaffeine.simulator.report.output=$(pwd)/simulation.md
        -Dcaffeine.simulator.files.paths.0="corda:trace_vaultservice.gz" -Dcaffeine.simulator.files.paths.1="lirs:loop.trace.gz"
        -Dcaffeine.simulator.files.paths.2="corda:trace_vaultservice.gz"

        '
    - continue-on-error: true
      name: Publish Simulator Results
      run: "{\n  echo '### Adaptivity'\n  echo '```'\n  cat $(pwd)/simulation.md\n\
        \  echo '```'\n} >> $GITHUB_STEP_SUMMARY\n"
    - continue-on-error: true
      name: Chart Simulation
      run: ./gradlew -q simulator:simulate --maximumSize=100,200,300
    - continue-on-error: true
      name: Memory Overhead
      run: ./gradlew -q caffeine:memoryOverhead
    - continue-on-error: true
      name: Stresser (read)
      run: 'timeout 1m ./gradlew -q caffeine:stress --workload=read || ([[ $? -eq
        124 ]] && echo "Timeout reached, but that''s OK")

        '
    - continue-on-error: true
      name: Stresser (write)
      run: 'timeout 1m ./gradlew -q caffeine:stress --workload=write || ([[ $? -eq
        124 ]] && echo "Timeout reached, but that''s OK")

        '
    - continue-on-error: true
      name: Stresser (refresh)
      run: 'timeout 1m ./gradlew -q caffeine:stress --workload=refresh || ([[ $? -eq
        124 ]] && echo "Timeout reached, but that''s OK")

        '
    - continue-on-error: true
      name: Write-behind (rxjava)
      run: ./gradlew build
      working-directory: examples/write-behind-rxjava
    - continue-on-error: true
      name: Coalescing Bulkloader (reactor)
      run: ./gradlew build
      working-directory: examples/coalescing-bulkloader-reactor
    - continue-on-error: true
      name: Hibernate (jcache)
      run: ./gradlew build
      working-directory: examples/hibernate
    - continue-on-error: true
      name: Resilience (failsafe)
      run: ./gradlew build
      working-directory: examples/resilience-failsafe
    - continue-on-error: true
      env:
        SNAPSHOT: true
      name: Prepare for Graal Native Image
      uses: ./.github/actions/run-gradle
      with:
        arguments: -q caffeine:clean caffeine:jar
        java: GraalVM
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      env:
        SNAPSHOT: true
      name: Graal Native Image
      uses: ./.github/actions/run-gradle
      with:
        arguments: '--project-dir examples/graal-native -Pagent run metadataCopy --task
          run --dir src/main/resources/META-INF/native-image nativeRun nativeTest

          '
        java: GraalVM
        token: ${{ secrets.GITHUB_TOKEN }}
name: examples
on:
  repository_dispatch:
    types: trigger-ga___examples.yml
permissions: read-all
