env:
  ALLOWED_ENDPOINTS: 'api.github.com:443 github.com:443 objects.githubusercontent.com:443

    '
jobs:
  scan:
    name: gitleaks
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6
      with:
        allowed-endpoints: ${{ env.ALLOWED_ENDPOINTS }}
        disable-sudo: true
        egress-policy: block
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      with:
        fetch-depth: 0
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Run gitleaks
      uses: gitleaks/gitleaks-action@44c470ffc35caa8b1eb3e8012ca53c2f9bea4eb5
name: gitleaks
on:
  repository_dispatch:
    types: trigger-ga___gitleaks.yml
permissions: read-all
