jobs:
  validation:
    name: Validation
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6
      with:
        allowed-endpoints: 'downloads.gradle.org:443 downloads.gradle-dn.com:443 github.com:443
          services.gradle.org:443

          '
        disable-sudo: true
        egress-policy: block
    - continue-on-error: true
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      uses: gradle/actions/wrapper-validation@db19848a5fa7950289d3668fb053140cf3028d43
name: Validate Gradle Wrapper
on:
  repository_dispatch:
    types: trigger-ga___gradle-wrapper-validation.yml
permissions: read-all
