env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
  JAVA_VERSION: 11
jobs:
  qodana:
    if: 'github.actor != ''dependabot[bot]'' && (github.event_name != ''pull_request''
      || github.event.pull_request.head.repo.fork == false)

      '
    permissions:
      actions: read
      checks: write
      contents: read
      security-events: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6
      with:
        allowed-endpoints: 'api.adoptium.net:443 api.foojay.io:443 api.github.com:443
          auth.docker.io:443 caffeine.gradle-enterprise.cloud:443 checkerframework.org:443
          docs.oracle.com:443 download.jetbrains.com:443 download-cdn.jetbrains.com:443
          downloads.gradle.org:443 downloads.gradle-dn.com:443 errorprone.info:443
          github.com:443 guava.dev:443 jcenter.bintray.com:443 lightbend.github.io:443
          objects.githubusercontent.com:443 packages.jetbrains.team:443 pkg-cdn.jetbrains.team:443
          plugins.gradle.org:443 plugins.jetbrains.com:443 plugins-artifacts.gradle.org:443
          prod.fus.aws.intellij.net:443 production.cloudflare.docker.com:443 registry-1.docker.io:443
          repo.gradle.org:443 repo.maven.apache.org:443 repo1.maven.org:443 resources.jetbrains.com:443
          services.gradle.org:443

          '
        disable-sudo: true
        egress-policy: block
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      name: Build
      uses: ./.github/actions/run-gradle
      with:
        arguments: build -x test
        java: ${{ env.JAVA_VERSION }}
    - continue-on-error: true
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      name: Qodana - Code Inspection
      uses: JetBrains/qodana-action@32840fdb87f8dd110e0a6b09323c7142b667b25d
      with:
        upload-result: true
    - continue-on-error: true
      name: Upload SARIF file for GitHub Advanced Security Dashboard
      uses: github/codeql-action/upload-sarif@2e230e8fe0ad3a14a340ad0815ddb96d599d2aff
      with:
        sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
name: Qodana
on:
  repository_dispatch:
    types: trigger-ga___qodana.yml
permissions: read-all
