env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
  JAVA_VERSION: 11
jobs:
  release:
    if: github.event.repository.fork == false
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6
      with:
        disable-sudo: true
        egress-policy: audit
    - continue-on-error: true
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      env:
        ORG_GRADLE_PROJECT_signingKey: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.OSSRH_GPG_SECRET_KEY_ID }}
        ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD
          }}
        ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.NEXUS_PASSWORD }}
        ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.NEXUS_USERNAME }}
      name: Releasing
      uses: ./.github/actions/run-gradle
      with:
        arguments: 'publishToSonatype closeAndReleaseSonatypeStagingRepository -Prelease
          --no-configuration-cache

          '
        java: ${{ env.JAVA_VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
name: release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
permissions: read-all
