jobs:
  misspell:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6
      with:
        allowed-endpoints: 'api.github.com:443 github.com:443

          '
        disable-sudo: true
        egress-policy: block
    - continue-on-error: true
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      name: Misspell
      uses: reviewdog/action-misspell@8cd4a880dd86b1b175092c18c23cdec31283d654
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-check
  typos:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6
      with:
        allowed-endpoints: 'github.com:443 objects.githubusercontent.com:443

          '
        disable-sudo: true
        egress-policy: block
    - continue-on-error: true
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      name: Typos
      uses: crate-ci/typos@8382594ee09667379b652553cf57daebb8176a3f
name: spelling
on:
  repository_dispatch:
    types: trigger-ga___spelling.yml
permissions: read-all
