jobs:
  trivy:
    permissions:
      actions: read
      checks: write
      contents: read
      security-events: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Harden Runner
      uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6
      with:
        allowed-endpoints: 'api.github.com:443 ghcr.io:443 github.com:443 pkg-containers.githubusercontent.com:443

          '
        disable-sudo: true
        egress-policy: block
    - continue-on-error: true
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
    - continue-on-error: true
      name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@595be6a0f6560a0a8fc419ddf630567fc623531d
      with:
        format: sarif
        output: trivy-results.sarif
        scan-type: fs
    - continue-on-error: true
      name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@2e230e8fe0ad3a14a340ad0815ddb96d599d2aff
      with:
        sarif_file: trivy-results.sarif
name: trivy
on:
  repository_dispatch:
    types: trigger-ga___trivy.yml
permissions: read-all
